### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by ZephyrShannon** [satoshi-pes/gnsstime.py#1]
HI, Satoshi-pes:
    I'm using your codes in China, And we live in timezone +8. And I find some problems using your codes.
    dt_gpst0 = dt.datetime(1980,1,6), is actually 1980-01-06 00:00:00+0800.
    I think you can fixed it with : datetime.datetime.strptime('1980-01-06 00:00:00+0000, "%Y-%m-%d %H:%M:%S%z")

**Comment by satoshi-pes** [comment]
Thank you for creating the issue! I fixed it.
